name: Main Workflow
on: [push, pull_request]
env:
  LLVM_VERSION: 13
jobs:
  debug:
    runs-on: ubuntu-latest
    container: ghcr.io/opencyphal/toolshed:ts22.4.1
    strategy:
      matrix:
        build_type: [Debug]
        target: [native]
        compiler: [gcc, clang]
    steps:
      - uses: actions/checkout@v3
      - run: test/ci/verify.py -v
                          --target ${{matrix.target}}
                          --build-type ${{ matrix.build_type }}
                          --toolchain-family ${{ matrix.compiler }}
                          configure
                          --omit-style-check-from-all
      - run: test/ci/verify.py -v
                          --target ${{matrix.target}}
                          --build-type ${{ matrix.build_type }}
                          --toolchain-family ${{ matrix.compiler }}
                          build
      - run: test/ci/verify.py -v
                          --target ${{matrix.target}}
                          --build-type ${{ matrix.build_type }}
                          --toolchain-family ${{ matrix.compiler }}
                          compile-test
      - run: test/ci/verify.py -v
                          --target ${{matrix.target}}
                          --build-type ${{ matrix.build_type }}
                          --toolchain-family ${{ matrix.compiler }}
                          test
                          test_all
